base_lr: 0.1
batch_size: 16
config: ./config/nturgbd-cross-view/train_joint.yaml
device: 0
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.aagcn_DAT.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 60
  num_person: 2
  num_point: 25
model_saved_name: ./runs/ntu_cv_agcn_joint
nesterov: true
num_epoch: 100
num_worker: 32
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: train
print_log: true
save_interval: 1
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 40
- 50
test_batch_size: 64
test_feeder_args:
  data_path: ./data/ntu/xview/val_data_joint_new.npy
  label_path: ./data/ntu/xview/val_label_new.pkl
train_feeder_args:
  data_path: ./data/ntu/xview/train_data_joint_new.npy
  debug: false
  label_path: ./data/ntu/xview/train_label_new.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: 100
warm_up_epoch: 0
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/ntu/xview/agcn_joint
